### ISSUE TITLE
How can I pass header

### ISSUE THREAD

**Issue by chiragpurohit71085** [bmutinda/HttpBuster#6]
Hi 

How can I pass header parameters?

Regards,

**Comment by bmutinda** [comment]
Hi @chiragpurohit71085.. Sorry its not documented anywhere but I will add it. 
This is how you add header....
NB: Header is added in the ```Api```

**1.** Before building HttpBuster

```java
Api api = new Api();
api.setEndpoint("https://example.com/api/");
api.addHeader( new ApiHeader("key_here", "value_here"));  
HttpBuster httpBuster = HttpBuster.withApi(api).build();  
```

**2.** After building HttpBuster
```java
httpBuster.getApi().addHeader()
```

**Comment by chiragpurohit71085** [comment]
HI 

Thanks. Let me try

**Comment by bmutinda** [comment]
@chiragpurohit71085  let me know if its now sorted i close the issue.
Thanks.

**Comment by chiragpurohit71085** [comment]
Thanks. This is what  Exactly I am looking for.
