### ISSUE TITLE
Help for getting latest version

### ISSUE THREAD

**Issue by chiragpurohit71085** [bmutinda/HttpBuster#7]
Hi

I have added following lines in my build.gradle (project level)

allprojects {
    repositories {
        jcenter()
        maven { url "https://jitpack.io" }
    }
}

and 

dependencies {

.............
 compile 'com.github.bmutinda:httpbuster:1.0'
.......

}

1) How I can know latest version of library?

I have tried 

 compile 'com.github.bmutinda:httpbuster:1.3.2'

by checking release tab of git but then it started giving following error...

Error:(63, 97) error: <anonymous com.httpbusterdemo.MainActivity$1> is not abstract and does not override abstract method done(BusterResponse,JSONObject,Exception) in ApiCallback

2) I am not able to use following method for 

 compile 'com.github.bmutinda:httpbuster:1.3.2' 

, I think this is due to version issue.

 httpBuster.makeMultipartRequest("photo-upload/", map, files, new ApiCallback() {
            @Override
            public void done(BusterResponse response, JSONObject jsonObject, Exception exception) {
                Log.e(TAG,  "POST MULTIPART - Response =" +(response!=null? response.getString() :"Not reachable" ));
            }
        });

it says can not resolve BusterResponse

Regards,

**Comment by chiragpurohit71085** [comment]
I got working by

 httpBuster.makeGetRequest("account/verify_credentials.json", null, new ApiCallback()
        {
            @Override
            public void done(BusterResponse busterResponse, JSONObject jsonObject, Exception e)
            {

                Log.e("Basic request ", "GET without params done");
                Log.e("jsonObject ", ""+jsonObject);
                Log.e("exception ", ""+e);


            }
        });

now just the first point, how I can know the latest version.

**Comment by bmutinda** [comment]
hi @chiragpurohit71085 
Its in the description [Latest Version](https://github.com/bmutinda/HttpBuster/#latest-version-)

**Comment by chiragpurohit71085** [comment]
Ok. Got it.
